# Pie OS - mkinitcpio.conf
# SEM autodetect: inclui TODOS os módulos

MODULES=(intel_agp i915 evdev usbhid hid usb_storage ehci-pci xhci-pci ahci ata_piix)
BINARIES=()
FILES=()
HOOKS=(base udev modconf block keyboard keymap plymouth filesystems fsck)
