#
# Pie OS - pacman.conf (sistema instalado, não live)
#

[options]
HoldPkg      = pacman glibc
Architecture = auto
SigLevel     = Required DatabaseOptional
ParallelDownloads = 5

[multilib]
Include = /etc/pacman.d/mirrorlist

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist
